[theme]
base = "light"
primaryColor = "#0B3D91"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4FA"
textColor = "#212121"
font = "sans serif"

[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
